### ISSUE TITLE
Missing comparison operators in logic_compare block

### ISSUE THREAD

**Issue by hfnovember** [google/blockly-android#708] opened 2017-12-07 21:14 UTC
The following arithmetic operators appear in Blockly's developer tools, but are unavailable in the current Android version of Blockly:

More than (>)
Less than (<)
More than or equal (>=)
Less than or equal (<=)

Only the following two operators are available:

Equal (==)
Not Equal (!=)

These operators should be available in <block type="logic_compare"></block>

**Comment by AnmAtAnm** [comment] 2017-12-08 05:35
Duplicate of #295. These operators require a translation layer because of their dependence on the left-to-right or right-to-left text.

**Closed by AnmAtAnm** 2017-12-08 05:35 UTC
